mysql:
  db_name: metaverse
  port: 3306
  url: mc_mysql
  user: root
  pass: password
econ:
  login_money: 500
world:
  traptower: public
traptower:
  money: 200
  pos:
    - spawn:
        x: 24
        y: 6
        z: 17
      init:
        x: 27
        y: 5
        z: 21
    - spawn:
        x: 30
        y: 6
        z: -47
      init:
        x: 33
        y: 5
        z: -43
    - spawn:
        x: 92
        y: 6
        z: -40
      init:
        x: 95
        y: 5
        z: -36
discord:
  warn_channel: 875995533821505567
