name: MetaversePlugin
version: '${project.version}'
main: world.arainu.core.metaverseplugin.MetaversePlugin
api-version: 1.17
authors: [ kumitatepazuru, kawattii, AreaEffectCloud ]
description: あらいぬメタバースプロジェクトマインクラフトサーバーのプラグイン
website: https://arainu.world
depend:
  - Vault
commands:
  worldtp:
    description: ワールド移動をするGUIを表示します。
    usage: /worldtp
    aliases:
      - wtp
    permission: metaverse.command.worldtp
  iphone:
    description: サーバー内で使用できるスマホを表示します。
    usage: /iphone
    permission: metaverse.command.iphone
  spawn:
    description: プラグイン特有のmobをスポーンさせます。
    usage: /spawn [type]
    permission: metaverse.command.spawn
permissions:
  metaverse.command.worldtp:
    default: op
  metaverse.command.iphone:
    default: true
  metaverse.command.spawn:
    default: op
