name: MetaversePlugin
version: '${project.version}'
main: world.arainu.core.metaverseplugin.MetaversePlugin
api-version: 1.17
authors: [ kumitatepazuru, kawattii, AreaEffectCloud, JolTheGreat ]
description: あらいぬメタバースプロジェクトマインクラフトサーバーのプラグイン
website: https://arainu.world
depend:
  - Vault
  - floodgate
  - DiscordSRV
  - AdvancedBan
softdepend:
  - Multiverse-Core
commands:
  worldtp:
    description: ワールド移動をするGUIを表示します。
    usage: /worldtp
    aliases:
      - wtp
    permission: metaverse.command.worldtp
  iphone:
    description: サーバー内で使用できるスマホを表示します。
    usage: /iphone
    permission: metaverse.command.iphone
  spawn:
    description: プラグイン特有のmobをスポーンさせます。
    usage: /spawn [type]
    permission: metaverse.command.spawn
  __back:
    description: サバイバルサーバーへ転送
    usage: /__back [player]
    permission: metaverse.command.backend
permissions:
  metaverse.command.worldtp:
    default: op
  metaverse.command.iphone:
    default: true
  metaverse.command.spawn:
    default: op
  metaverse.command.backend:
    default: op
