name: MetaversePlugin
version: '${project.version}'
main: world.arainu.core.metaverseplugin.MetaversePlugin
api-version: 1.17
authors: [ kumitatepazuru, kawattii ]
description: あらいぬメタバースプロジェクトマインクラフトサーバーのプラグイン
website: http://arainu.world
