# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: deploy

on:
  workflow_run:
    branches:
      - master
    workflows:
      - build
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.SSH_USERNAME }}
          server: ${{ secrets.SSH_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './target/Metaverseplugin.jar'
          remote_path: '/home/riku/minecraft/plugins/'
          args: '-o ConnectTimeout=5'
